AllCops:
  TargetRubyVersion: 2.3
  TargetRailsVersion: 5.2
  Exclude:
    - 'Rakefile'

Rails:
  Enabled: true

Rails/Date:
  Enabled: false

# Don't enforce documentation
Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'test/**/*'

Metrics/LineLength:
  Max: 140
  Exclude:
    - 'test/**/*'

Metrics/MethodLength:
  Max: 40

Naming/AccessorMethodName:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Metrics/ClassLength:
  Max: 500

Naming/FileName:
  Exclude:
      - 'db/seeds.d/*'

Style/WordArray:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/EachWithObject:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Style/CommentedKeyword:
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Enabled: false
