AllCops:
  TargetRubyVersion: 2.2
  Exclude:
    - 'Rakefile'

Rails:
  Enabled: true

# Don't enforce documentation
Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/LineLength:
  Max: 221
  Exclude:
    - 'puppetdb_foreman.gemspec'

Style/Next:
  Enabled: false

# Support both ruby19 and hash_rockets
Style/HashSyntax:
  Enabled: false

# SupportedStyles: format, sprintf, percent
Style/FormatString:
  Enabled: false

Naming/MethodName:
  Enabled: false

Metrics/AbcSize:
  Max: 50

Metrics/ClassLength:
  Max: 200

Rails/Date:
  Exclude:
    - 'puppetdb_foreman.gemspec'

Metrics/BlockLength:
  Exclude:
    - 'config/routes.rb'
    - 'test/**/*'

Metrics/MethodLength:
  Max: 50

Style/ClassAndModuleChildren:
  Exclude:
    - 'app/models/setting/*'
    - 'test/controllers/api/v2/*'

Style/RegexpLiteral:
  Exclude:
    - 'config/routes.rb'

Rails/HttpPositionalArguments:
  Enabled: false

Rails/SkipsModelValidations:
  Exclude:
    - 'app/services/puppetdb_host.rb'

Style/SymbolArray:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Lint/BooleanSymbol:
  Enabled: false
