inherit_gem:
  theforeman-rubocop:
    - default.yml

AllCops:
  TargetRubyVersion: '2.7'

Layout/LineLength:
  Exclude:
    - 'test/**/*'

Metrics/BlockLength:
  Exclude:
    - 'lib/puppetdb_foreman/engine.rb'
    - 'test/**/*'

Metrics/ClassLength:
  Exclude:
    - 'test/**/*'
